version = 0.1
[default.deploy.parameters]
stack_name = "travel-ai-platform"
resolve_s3 = true
s3_prefix = "travel-ai-platform"
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
